/* Generated By:JavaCC: Do not edit this line. LuaParser.java */
package parser;

import util.*;
import core.*;
import java.util.*;

public class LuaParser implements LuaParserConstants {

        public static Trecho parse(java.io.File file) {
                LuaParser parser;
                Trecho trecho = null;
                System.out.println("Lua PLP Parser Version 0.0.1: Reading from file " + file.getName() + "...");
                try {
                        parser = new LuaParser(new java.io.FileInputStream(file));
                } catch (java.io.FileNotFoundException e) {
                        System.out.println("Lua PLP Parser Version 0.0.1: File " + file.getName() + " not found.");
                        return null;
                }
                try {
                        trecho = parser.Trecho();
                        System.out.println("Lua PLP Parser Version 0.0.1: Lua program parsed successfully.");
                } catch (ParseException e) {
                        System.out.println("Lua PLP Parser Version 0.0.1: Encountered errors during parse.");
                        System.out.println(e.getMessage());
                }
                return trecho;
        }

  private static Exp.VarExp assertvarexp(Exp.ExpPrimaria pe) throws ParseException {
        if (!pe.isvarexp())
                throw new ParseException("expected variable");
        return (Exp.VarExp) pe;
  }

  private static Exp.ChamadaFunc assertfunccall(Exp.ExpPrimaria pe) throws ParseException {
        if (!pe.isfunccall())
                throw new ParseException("expected function call");
        return (Exp.ChamadaFunc) pe;
  }

/** Root production. */
  final public Trecho Trecho() throws ParseException {
        Bloco b;
        Trecho t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 69:
      jj_consume_token(69);
             token_source.SwitchTo(IN_COMMENT);
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
    b = Bloco();
    jj_consume_token(0);
                                                                    t=new Trecho(b); {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  final public Bloco Bloco() throws ParseException {
        Bloco b = new Bloco();
        Comando c;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DO:
      case FOR:
      case FUNCTION:
      case IF:
      case WHILE:
      case NAME:
      case 70:
      case 75:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_1;
      }
      c = Comando();
                      b.add(c);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case RETURN:
      c = ReturnComando();
                                                       b.add(c);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
                                                                     {if (true) return b;}
    throw new Error("Missing return statement in function");
  }

  final public Comando Comando() throws ParseException {
        Bloco b;
        Exp e,e2,e3=null;
        Comando c;
        Token n;
        FuncNome fn;
        FuncCorpo fb;
        List<Nome> nl;
        List<Exp> el=null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 70:
      jj_consume_token(70);
             {if (true) return null;}
      break;
    case DO:
      jj_consume_token(DO);
      b = Bloco();
      jj_consume_token(END);
                                c=Comando.bloco(b); {if (true) return c;}
      break;
    case WHILE:
      jj_consume_token(WHILE);
      e = Exp();
      jj_consume_token(DO);
      b = Bloco();
      jj_consume_token(END);
                                               c=Comando.whiledo(e,b); {if (true) return c;}
      break;
    case NAME:
    case 75:
      c = ExprComando();
                          {if (true) return c;}
      break;
    case IF:
      c = IfThenElse();
                          {if (true) return c;}
      break;
    default:
      jj_la1[4] = jj_gen;
      if (jj_2_1(3)) {
        jj_consume_token(FOR);
        n = jj_consume_token(NAME);
        jj_consume_token(71);
        e = Exp();
        jj_consume_token(72);
        e2 = Exp();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 72:
          jj_consume_token(72);
          e3 = Exp();
          break;
        default:
          jj_la1[3] = jj_gen;
          ;
        }
        jj_consume_token(DO);
        b = Bloco();
        jj_consume_token(END);
                                                                                                     c=Comando.fornumerico(n.image,e,e2,e3,b); {if (true) return c;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case FUNCTION:
          jj_consume_token(FUNCTION);
          fn = FuncNome();
          fb = FuncCorpo();
                                                   c=Comando.deffuncao(fn,fb); {if (true) return c;}
          break;
        case FOR:
          jj_consume_token(FOR);
          nl = ListaNome();
          jj_consume_token(IN);
          el = ExpList();
          jj_consume_token(DO);
          b = Bloco();
          jj_consume_token(END);
                                                                       c=Comando.forgenerico(nl,el,b); {if (true) return c;}
          break;
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Comando IfThenElse() throws ParseException {
        Bloco b,b2,b3=null;
        Exp e,e2;
        List<Exp> el=null;
        List<Bloco> bl=null;
    jj_consume_token(IF);
    e = Exp();
    jj_consume_token(THEN);
    b = Bloco();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSEIF:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_2;
      }
      jj_consume_token(ELSEIF);
      e2 = Exp();
      jj_consume_token(THEN);
      b2 = Bloco();
                        if (el==null) el=new ArrayList<Exp>();
                        if (bl==null) bl=new ArrayList<Bloco>();
                        el.add(e2);
                        bl.add(b2);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      b3 = Bloco();
      break;
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    jj_consume_token(END);
                          {if (true) return Comando.ifthenelse(e,b,el,bl,b3);}
    throw new Error("Missing return statement in function");
  }

  final public Comando ReturnComando() throws ParseException {
        List<Exp> el=null;
        Comando c;
    jj_consume_token(RETURN);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FALSE:
    case NIL:
    case NOT:
    case TRUE:
    case NAME:
    case NUMBER:
    case STRING:
    case 69:
    case 75:
    case 80:
    case 83:
      el = ExpList();
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 70:
      jj_consume_token(70);
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
                                           c=Comando.returncomando(el); {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  final public Comando ExprComando() throws ParseException {
        Exp.ExpPrimaria p;
        Comando c=null;
    p = ExpPrimaria();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 71:
    case 72:
      c = Atribui(assertvarexp(p));
      break;
    default:
      jj_la1[10] = jj_gen;
      ;
    }
         if(c==null){c=Comando.chamadafunc(assertfunccall(p));}{if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  final public Comando Atribui(Exp.VarExp v0) throws ParseException {
        List<Exp.VarExp> vl = new ArrayList<Exp.VarExp>();
        vl.add(v0);
        Exp.VarExp ve;
        List<Exp> el;
        Comando c;
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 72:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_3;
      }
      jj_consume_token(72);
      ve = VarExp();
                          vl.add(ve);
    }
    jj_consume_token(71);
    el = ExpList();
                                                           c=Comando.atribuicao(vl,el); {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  final public Exp Exp() throws ParseException {
        Exp e,s;
        int op;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FALSE:
    case NIL:
    case TRUE:
    case NAME:
    case NUMBER:
    case STRING:
    case 75:
    case 80:
      e = SimpleExp();
      break;
    case NOT:
    case 69:
    case 83:
      op = Unop();
      s = Exp();
                                            e=Exp.expunaria(op,s);
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_4:
    while (true) {
      if (jj_2_2(2)) {
        ;
      } else {
        break label_4;
      }
      op = Binop();
      s = Exp();
                                          e=Exp.expbinaria(e,op,s);
    }
                                                                        {if (true) return e;}
    throw new Error("Missing return statement in function");
  }

  final public Exp SimpleExp() throws ParseException {
        Token n;
        Exp e;
        ConstrutorTabela c;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NIL:
      jj_consume_token(NIL);
                                                          e=new LuaNil(); {if (true) return e;}
      break;
    case TRUE:
      jj_consume_token(TRUE);
                                                          e=new LuaBoolean(true); {if (true) return e;}
      break;
    case FALSE:
      jj_consume_token(FALSE);
                                                          e=new LuaBoolean(false); {if (true) return e;}
      break;
    case NUMBER:
      n = jj_consume_token(NUMBER);
                                                          e=new LuaNumber(Integer.parseInt(n.toString())); {if (true) return e;}
      break;
    case STRING:
      e = Str();
                                                          {if (true) return e;}
      break;
    case 80:
      c = ConstrutorTabela();
                                          e=Exp.construtortabela(c); {if (true) return e;}
      break;
    case NAME:
    case 75:
      e = ExpPrimaria();
                                                  {if (true) return e;}
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Exp.VarExp VarExp() throws ParseException {
        Exp.ExpPrimaria p;
    p = ExpPrimaria();
                         {if (true) return assertvarexp(p);}
    throw new Error("Missing return statement in function");
  }

  final public Exp.ExpPrimaria ExpPrimaria() throws ParseException {
        Exp.ExpPrimaria p;
    p = ExpPrefixa();
    label_5:
    while (true) {
      if (jj_2_3(2)) {
        ;
      } else {
        break label_5;
      }
      p = OpPosFixo(p);
    }
                                                       {if (true) return p;}
    throw new Error("Missing return statement in function");
  }

  final public Exp.ExpPrimaria OpPosFixo(Exp.ExpPrimaria lhs) throws ParseException {
        Token n;
        Exp e;
        FuncArgs a;
        Exp.ExpPrimaria p;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STRING:
    case 75:
      a = FuncArgs();
                      p=Exp.functionop(lhs, a); {if (true) return p;}
      break;
    case 73:
      jj_consume_token(73);
      e = Exp();
      jj_consume_token(74);
                          p=Exp.indexop(lhs, e); {if (true) return p;}
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Exp.ExpPrimaria ExpPrefixa() throws ParseException {
        Token n;
        Exp e;
        Exp.ExpPrimaria p;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      n = jj_consume_token(NAME);
                                   p=Exp.nomeprefix(n.image); {if (true) return p;}
      break;
    case 75:
      jj_consume_token(75);
      e = Exp();
      jj_consume_token(76);
                           p=Exp.parensprefix(e); {if (true) return p;}
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public List<Exp> ExpList() throws ParseException {
        List<Exp> l = new ArrayList<Exp>();
        Exp e;
    e = Exp();
                 l.add(e);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 72:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_6;
      }
      jj_consume_token(72);
      e = Exp();
                                          l.add(e);
    }
                                                        {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public FuncArgs FuncArgs() throws ParseException {
        List<Exp> el=null;
        LuaString s;
        FuncArgs a;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 75:
      jj_consume_token(75);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FALSE:
      case NIL:
      case NOT:
      case TRUE:
      case NAME:
      case NUMBER:
      case STRING:
      case 69:
      case 75:
      case 80:
      case 83:
        el = ExpList();
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      jj_consume_token(76);
                                  a=FuncArgs.explist(el); {if (true) return a;}
      break;
    case STRING:
      s = Str();
                                                  a=FuncArgs.string(s); {if (true) return a;}
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public FuncNome FuncNome() throws ParseException {
        Token n;
        FuncNome f;
    n = jj_consume_token(NAME);
                  f=new FuncNome(n.image);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 77:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_7;
      }
      jj_consume_token(77);
      n = jj_consume_token(NAME);
                                f.addponto(n.image);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 78:
      jj_consume_token(78);
      n = jj_consume_token(NAME);
                                f.metodo=n.image;
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
                         {if (true) return f;}
    throw new Error("Missing return statement in function");
  }

  final public FuncCorpo FuncCorpo() throws ParseException {
        ParList pl=null;
        Bloco b;
        FuncCorpo f;
    jj_consume_token(75);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
    case 79:
      pl = ParList();
      break;
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    jj_consume_token(76);
    b = Bloco();
    jj_consume_token(END);
                                                   f=new FuncCorpo(pl,b); {if (true) return f;}
    throw new Error("Missing return statement in function");
  }

  final public ParList ParList() throws ParseException {
        List<Nome> l=null;
        boolean v=false;
        ParList p;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAME:
      l = ListaNome();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 72:
        jj_consume_token(72);
        jj_consume_token(79);
                                  v=true;
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
                                              p=new ParList(l,v); {if (true) return p;}
      break;
    case 79:
      jj_consume_token(79);
                  p=new ParList(null,true); {if (true) return p;}
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public List<Nome> ListaNome() throws ParseException {
        List<Nome> l = new ArrayList<Nome>();
        Token nome;
    nome = jj_consume_token(NAME);
                     l.add(new Nome(nome.image));
    label_8:
    while (true) {
      if (jj_2_4(2)) {
        ;
      } else {
        break label_8;
      }
      jj_consume_token(72);
      nome = jj_consume_token(NAME);
                                                                                  l.add(new Nome(nome.image));
    }
                                                                                                                   {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public ConstrutorTabela ConstrutorTabela() throws ParseException {
        ConstrutorTabela c = new ConstrutorTabela();
        List<CampoTabela> l = null;
    jj_consume_token(80);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FALSE:
    case NIL:
    case NOT:
    case TRUE:
    case NAME:
    case NUMBER:
    case STRING:
    case 69:
    case 73:
    case 75:
    case 80:
    case 83:
      l = ListaCampos();
                               c.campos=l;
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    jj_consume_token(81);
                                                    {if (true) return c;}
    throw new Error("Missing return statement in function");
  }

  final public List<CampoTabela> ListaCampos() throws ParseException {
        List<CampoTabela> l = new ArrayList<CampoTabela>();
        CampoTabela f;
    f = Campo();
                   l.add(f);
    label_9:
    while (true) {
      if (jj_2_5(2)) {
        ;
      } else {
        break label_9;
      }
      CampoSep();
      f = Campo();
                                                                  l.add(f);
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 70:
    case 72:
      CampoSep();
      break;
    default:
      jj_la1[25] = jj_gen;
      ;
    }
                                                                                               {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final public CampoTabela Campo() throws ParseException {
        Token nome;
        Exp exp,rhs;
        CampoTabela f;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 73:
      jj_consume_token(73);
      exp = Exp();
      jj_consume_token(74);
      jj_consume_token(71);
      rhs = Exp();
                                                                  f=CampoTabela.campoChaveado(exp,rhs); {if (true) return f;}
      break;
    default:
      jj_la1[26] = jj_gen;
      if (jj_2_6(2)) {
        nome = jj_consume_token(NAME);
        jj_consume_token(71);
        rhs = Exp();
                                                                  f=CampoTabela.campoNomeado(nome.image,rhs); {if (true) return f;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case FALSE:
        case NIL:
        case NOT:
        case TRUE:
        case NAME:
        case NUMBER:
        case STRING:
        case 69:
        case 75:
        case 80:
        case 83:
          rhs = Exp();
                                                                  f=CampoTabela.listCampos(rhs);  {if (true) return f;}
          break;
        default:
          jj_la1[27] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public void CampoSep() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 72:
      jj_consume_token(72);
      break;
    case 70:
      jj_consume_token(70);
      break;
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public int Binop() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 82:
      jj_consume_token(82);
                        {if (true) return LuaOps.OP_ADD;}
      break;
    case 83:
      jj_consume_token(83);
                        {if (true) return LuaOps.OP_SUB;}
      break;
    case 84:
      jj_consume_token(84);
                        {if (true) return LuaOps.OP_MUL;}
      break;
    case 85:
      jj_consume_token(85);
                        {if (true) return LuaOps.OP_DIV;}
      break;
    case 86:
      jj_consume_token(86);
                        {if (true) return LuaOps.OP_POW;}
      break;
    case 87:
      jj_consume_token(87);
                        {if (true) return LuaOps.OP_MOD;}
      break;
    case 88:
      jj_consume_token(88);
                        {if (true) return LuaOps.OP_CONCAT;}
      break;
    case 89:
      jj_consume_token(89);
                        {if (true) return LuaOps.OP_LT;}
      break;
    case 90:
      jj_consume_token(90);
                        {if (true) return LuaOps.OP_LE;}
      break;
    case 91:
      jj_consume_token(91);
                        {if (true) return LuaOps.OP_GT;}
      break;
    case 92:
      jj_consume_token(92);
                        {if (true) return LuaOps.OP_GE;}
      break;
    case 93:
      jj_consume_token(93);
                        {if (true) return LuaOps.OP_EQ;}
      break;
    case 94:
      jj_consume_token(94);
                        {if (true) return LuaOps.OP_NEQ;}
      break;
    case AND:
      jj_consume_token(AND);
                        {if (true) return LuaOps.OP_AND;}
      break;
    case OR:
      jj_consume_token(OR);
                        {if (true) return LuaOps.OP_OR;}
      break;
    default:
      jj_la1[29] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public int Unop() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 83:
      jj_consume_token(83);
                        {if (true) return LuaOps.OP_UNM;}
      break;
    case NOT:
      jj_consume_token(NOT);
                        {if (true) return LuaOps.OP_NOT;}
      break;
    case 69:
      jj_consume_token(69);
                        {if (true) return LuaOps.OP_LEN;}
      break;
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public LuaString Str() throws ParseException {
  Token n;
    n = jj_consume_token(STRING);
    String tokenStr = n.toString();
    tokenStr = tokenStr.substring(1, tokenStr.length() - 1);
    {if (true) return new LuaString(tokenStr);}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(NIL)) return true;
    return false;
  }

  private boolean jj_3R_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) return true;
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(69)) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(NOT)) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(83)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) return true;
    }
    }
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_10()) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_36()) return true;
    return false;
  }

  private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(OR)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(AND)) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_scan_token(94)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_scan_token(93)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_scan_token(92)) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_3R_51()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(91)) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_scan_token(90)) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_scan_token(89)) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_scan_token(88)) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_3R_56()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_scan_token(87)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_scan_token(86)) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(85)) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(84)) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(83)) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(75)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_54()) jj_scanpos = xsp;
    if (jj_scan_token(76)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) return true;
    }
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_scan_token(82)) return true;
    return false;
  }

  private boolean jj_3R_10() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_15()) {
    jj_scanpos = xsp;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(72)) return true;
    if (jj_scan_token(NAME)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_13()) return true;
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(71)) return true;
    return false;
  }

  private boolean jj_3R_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) {
    jj_scanpos = xsp;
    if (jj_scan_token(70)) return true;
    }
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_scan_token(75)) return true;
    return false;
  }

  private boolean jj_3R_57() {
    if (jj_scan_token(NAME)) return true;
    return false;
  }

  private boolean jj_3R_55() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) return true;
    }
    return false;
  }

  private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(73)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(73)) return true;
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) return true;
    }
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(80)) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_3R_55()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(71)) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_52()) return true;
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_3R_51()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public LuaParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[31];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x80000000,0x0,0x0,0x80000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20000000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0xc00b0,0x2000,0x0,0xc0080,0x30,0x2,0x1,0x20190c08,0x0,0x0,0x0,0x20190c08,0x20190408,0x20000000,0x80000,0x0,0x20190c08,0x20000000,0x0,0x0,0x80000,0x0,0x80000,0x20190c08,0x0,0x0,0x20190c08,0x0,0x1000,0x800,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x20,0x840,0x0,0x100,0x840,0x0,0x0,0x0,0x90820,0x40,0x180,0x100,0x90820,0x10800,0xa00,0x800,0x100,0x90820,0x800,0x2000,0x4000,0x8000,0x100,0x8000,0x90a20,0x140,0x200,0x90820,0x140,0x7ffc0000,0x80020,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[6];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public LuaParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public LuaParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new LuaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public LuaParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new LuaParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public LuaParser(LuaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(LuaParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 31; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[95];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 31; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 95; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 6; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
